import { useState } from 'react'
import { ChevronDown, Download, FileText, FileType2, Trash2, Upload } from 'lucide-react'

import { ConfirmDialog } from '@/components/common/ConfirmDialog'
import { FileDropzone } from '@/components/common/FileDropzone'
import { LoadingButton } from '@/components/common/LoadingButton'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import formatDate from '@/lib/formatDate'
import {
  useDeleteSignedDocument,
  useDownloadDocument,
  useDownloadDocumentWord,
  useDownloadSignedDocument,
  usePreviewSignedDocument,
  useUploadSignedDocument,
} from '../api'
import { followupFormatStage, PLAN_FORMATS } from '../lib/planStatus'
import type { Plan } from '../types'
import { ActaStatusBadge } from './PlanStatusBadge'

type PlanFormat = (typeof PLAN_FORMATS)[number]

interface PlanDocumentsProps {
  plan: Plan
  /**
   * Whether the viewer is the director who owns the plan. Only they upload the
   * signed copies — and only they take the signed acta back off, which is what
   * reopens the agreement for editing.
   */
  canManage: boolean
}

/**
 * The three official forms of a plan: download them for the handwritten
 * signatures and attach the signed scan back.
 *
 * Nothing here has to be generated by hand — the API renders each form from the
 * plan as it stands the moment it is asked for, and re-renders Formato 3 every
 * time a seguimiento is recorded.
 *
 * There is no separate "close the acta" step: the form always prints what the
 * plan currently says, so freezing it before signing bought nothing. Uploading
 * the signed Ficha de acuerdo is what settles the agreement and puts the plan
 * into force, and removing that scan is what opens it back up.
 *
 * @example
 * <PlanDocuments plan={plan} canManage={isDirector} />
 */
export function PlanDocuments({ plan, canManage }: PlanDocumentsProps) {
  const followupStage = followupFormatStage(plan)

  return (
    <section className="border-border bg-background overflow-hidden rounded-md border">
      <header className="flex flex-wrap items-center justify-between gap-3 border-b px-6 py-4">
        <div>
          <h2 className="font-semibold">Formatos oficiales</h2>
          <p className="text-muted-foreground text-sm">
            Descarga el formato, recoge las firmas y súbelo firmado.
          </p>
        </div>

        <ActaStatusBadge status={plan.acta_status} />
      </header>

      {plan.acta_locked && (
        <p className="bg-amber-50 px-6 py-2 text-sm text-amber-800 dark:bg-amber-950/30 dark:text-amber-200">
          Acuerdo firmado: el plan está en vigencia y el contenido del acta ya no se modifica. El
          seguimiento sigue su curso.
        </p>
      )}

      <ul className="divide-border divide-y">
        {PLAN_FORMATS.map((format) => (
          <FormatRow
            key={format.slug}
            plan={plan}
            format={format}
            canManage={canManage}
            // Formatos 1 and 2 are settled once they are drawn up; only
            // Formato 3 keeps moving with the seguimientos.
            followupStage={format.slug === 'formato-3' ? followupStage : null}
          />
        ))}
      </ul>
    </section>
  )
}

/**
 * One form of the plan. Every action is scoped to this row: downloading one
 * format must not put the other two in a pending state.
 */
function FormatRow({
  plan,
  format,
  canManage,
  followupStage,
}: {
  plan: Plan
  format: PlanFormat
  canManage: boolean
  /** Cut this form currently reflects, for the forms that track them. */
  followupStage: string | null
}) {
  const [uploading, setUploading] = useState(false)
  const [file, setFile] = useState<File | null>(null)
  const [confirmDelete, setConfirmDelete] = useState(false)

  const download = useDownloadDocument(plan.id)
  const downloadWord = useDownloadDocumentWord(plan.id)
  const downloadSigned = useDownloadSignedDocument(plan.id)
  const previewSigned = usePreviewSignedDocument(plan.id)
  const uploadSigned = useUploadSignedDocument(plan.id)
  const deleteSigned = useDeleteSignedDocument(plan.id)

  const record = plan.documents.find((entry) => entry.format_type === format.key)

  const isActa = format.slug === 'formato-2'

  // Signing the Ficha de acuerdo is what turns it into the copy of record, so
  // the acto administrativo backing it and at least one agreed commitment have
  // to be there first — the API refuses the upload otherwise, and saying so
  // here saves the director a round trip.
  const missingActaData = isActa
    ? [
        !plan.acta_number && 'el número del acta',
        !plan.acta_date && 'la fecha del acta',
        !plan.items.some((item) => item.commitment) && 'al menos un compromiso',
      ].filter((entry): entry is string => Boolean(entry))
    : []

  const actaIncomplete = missingActaData.length > 0

  // Copies signed before the API kept the uploaded name fall back to a generic
  // one, so the chip never renders an empty label.
  const signedName = record?.signed_filename ?? `${format.slug}_firmado.pdf`

  function submitSigned() {
    if (!file) return

    uploadSigned.mutate(
      { format: format.slug, file },
      {
        onSuccess: () => {
          setUploading(false)
          setFile(null)
        },
      },
    )
  }

  /**
   * The scan sits behind the Bearer token, so there is no URL to link to: the
   * tab is opened first — while the click is still a user gesture, or the popup
   * blocker eats it — and the blob is pushed into it once it lands.
   */
  function previewInNewTab() {
    const tab = window.open('', '_blank')

    previewSigned.mutate(format.slug, {
      onSuccess: (url) => {
        if (tab) tab.location.href = url
        else window.open(url, '_blank')

        // The tab holds the file by now; keeping the blob alive only leaks it.
        window.setTimeout(() => URL.revokeObjectURL(url), 60_000)
      },
      onError: () => tab?.close(),
    })
  }

  return (
    <li className="flex flex-wrap items-center gap-4 px-6 py-4">
      <FileText className="text-muted-foreground size-5 shrink-0" aria-hidden="true" />

      <div className="min-w-0 flex-1">
        <p className="flex flex-wrap items-center gap-2 text-sm font-medium">
          {format.name}
          {followupStage && <Badge variant="outline">Actualizado: {followupStage}</Badge>}
        </p>
        <p className="text-muted-foreground text-xs">{format.description}</p>

        {record?.signed_at && (
          <p className="text-muted-foreground mt-0.5 text-xs">
            Firmado el {formatDate(record.signed_at)}
          </p>
        )}
      </div>

      <div className="flex shrink-0 flex-wrap items-center gap-2">
        <DropdownMenu>
          <DropdownMenuTrigger
            render={
              <LoadingButton
                size="sm"
                pending={download.isPending || downloadWord.isPending}
                pendingLabel="Descargando…"
              >
                <Download className="size-4" aria-hidden="true" />
                Descargar
                <ChevronDown className="size-3.5" aria-hidden="true" />
              </LoadingButton>
            }
          />

          <DropdownMenuContent align="end">
            <DropdownMenuItem onClick={() => download.mutate(format.slug)}>
              <FileText className="size-4" aria-hidden="true" />
              Formato PDF
            </DropdownMenuItem>

            {/* Rendered on the fly from the plan as it stands: the working copy
                the director corrects before printing it for signature. The API
                keeps it to managers, so the teacher is not offered it. */}
            {canManage && (
              <DropdownMenuItem onClick={() => downloadWord.mutate(format.slug)}>
                <FileType2 className="size-4" aria-hidden="true" />
                Formato Word
              </DropdownMenuItem>
            )}
          </DropdownMenuContent>
        </DropdownMenu>

        {record?.has_signed ? (
          <div className="border-border bg-muted/40 flex max-w-full items-center gap-1 rounded-md border py-1 pr-1 pl-2.5">
            <FileText
              className="size-4 shrink-0 text-red-600 dark:text-red-400"
              aria-hidden="true"
            />

            <button
              type="button"
              onClick={previewInNewTab}
              disabled={previewSigned.isPending}
              title={`Previsualizar ${signedName} en una pestaña nueva`}
              className="max-w-56 min-w-0 cursor-pointer truncate text-sm underline-offset-2 hover:underline disabled:cursor-default disabled:opacity-60"
            >
              {signedName}
            </button>

            <LoadingButton
              size="icon-xs"
              variant="ghost"
              onClick={() => downloadSigned.mutate({ format: format.slug, filename: signedName })}
              pending={downloadSigned.isPending}
              aria-label={`Descargar ${signedName}`}
              title="Descargar el PDF firmado"
            >
              <Download className="size-3.5" aria-hidden="true" />
            </LoadingButton>

            {canManage && (
              <Button
                size="icon-xs"
                variant="ghost"
                onClick={() => setConfirmDelete(true)}
                aria-label={`Eliminar ${signedName}`}
                title="Eliminar el PDF firmado"
              >
                <Trash2 className="size-3.5" aria-hidden="true" />
              </Button>
            )}
          </div>
        ) : (
          canManage && (
            <Button
              size="sm"
              variant="outline"
              onClick={() => setUploading(true)}
              disabled={actaIncomplete}
              title={
                actaIncomplete
                  ? `Antes de firmar el acta falta registrar ${missingActaData.join(', ')}`
                  : undefined
              }
            >
              <Upload className="size-4" aria-hidden="true" />
              Subir firmado
            </Button>
          )
        )}
      </div>

      <Dialog
        open={uploading}
        onOpenChange={(open) => {
          if (!open) {
            setUploading(false)
            setFile(null)
          }
        }}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Subir {format.name} firmado</DialogTitle>
            <DialogDescription>
              Adjunta el PDF escaneado con las firmas. Reemplaza cualquier versión firmada anterior.
            </DialogDescription>
          </DialogHeader>

          <FileDropzone file={file} onFileChange={setFile} isUploading={uploadSigned.isPending} />

          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setUploading(false)}
              disabled={uploadSigned.isPending}
            >
              Cancelar
            </Button>
            <LoadingButton
              onClick={submitSigned}
              disabled={!file}
              pending={uploadSigned.isPending}
              pendingLabel="Subiendo…"
            >
              Subir
            </LoadingButton>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <ConfirmDialog
        open={confirmDelete}
        onOpenChange={setConfirmDelete}
        title="¿Eliminar el PDF firmado?"
        description={
          isActa
            ? 'El acuerdo volverá a estado borrador y podrás editar el plan de nuevo. El formato en blanco se conserva y se te pedirá otra vez la versión firmada.'
            : 'Se te pedirá de nuevo la versión firmada de este formato. El formato en blanco se conserva.'
        }
        confirmLabel="Eliminar"
        pendingLabel="Eliminando…"
        confirmVariant="destructive"
        isPending={deleteSigned.isPending}
        onConfirm={() =>
          deleteSigned.mutate(format.slug, { onSuccess: () => setConfirmDelete(false) })
        }
      />
    </li>
  )
}
