export { AdminPeriodsPage } from './AdminPeriodsPage'
export { default as PeriodCourseDetailPage } from './PeriodCourseDetailPage'
export { default as PeriodDetailPage } from './PeriodDetailPage'
export { default as PeriodsPage } from './PeriodsPage'
export { default as TeacherMateriasPage } from './TeacherMateriasPage'
